
export const API_URL = "http://127.0.0.1:5000"

export const UPLOAD_IMAGE_SUCCESS = "UPLOAD_IMAGE_SUCCESS"
export const UPLOAD_IMAGE_ERROR = "UPLOAD_IMAGE_ERROR"
export const UPLOAD_IMAGE_LOADER = "UPLOAD_IMAGE_LOADER"

export const SUBMIT_ANSWER_COM1_SUCCESS = "SUBMIT_ANSWER_COM1_SUCCESS"
export const SUBMIT_ANSWER_COM1_ERROR = "SUBMIT_ANSWER_COM1_ERROR"
export const SUBMIT_ANSWER_COM1_LOADER = "SUBMIT_ANSWER_COM1_LOADER"

export const SUBMIT_ANSWER_COM2_SUCCESS = "SUBMIT_ANSWER_COM2_SUCCESS"
export const SUBMIT_ANSWER_COM2_ERROR = "SUBMIT_ANSWER_COM2_ERROR"
export const SUBMIT_ANSWER_COM2_LOADER = "SUBMIT_ANSWER_COM2_LOADER"

export const SUBMIT_ANSWER_OTHER_SUCCESS = "SUBMIT_ANSWER_OTHER_SUCCESS"
export const SUBMIT_ANSWER_OTHER_ERROR = "SUBMIT_ANSWER_OTHER_ERROR"
export const SUBMIT_ANSWER_OTHER_LOADER = "SUBMIT_ANSWER_OTHER_LOADER"

export const CLEAR_QUESTION_DATA = "CLEAR_QUESTION_DATA"